/* Generated By:JavaCC: Do not edit this line. PostconditionConstants.java */
package kmade.kmade.adaptatorFC.parserExpression;

public interface PostconditionConstants {

  int EOF = 0;
  int REMOVE = 4;
  int SET = 5;
  int ADD = 6;
  int CREATE = 7;
  int REPLACE = 8;
  int GETVALUE = 9;
  int UNKNOWN_INT = 10;
  int UNKNOWN_STRING = 11;
  int UNKNOWN_BOOLEAN = 12;
  int VOID_TYPE = 13;
  int PARO = 14;
  int PARF = 15;
  int COMA = 16;
  int SEQUENCE = 17;
  int ASSIGNMENT = 18;
  int PLUS = 19;
  int MINUS = 20;
  int PLUS_ASSIGNMENT = 21;
  int MINUS_ASSIGNMENT = 22;
  int EOL = 23;
  int DIGIT = 24;
  int LETTER = 25;
  int BOOLEAN = 26;
  int INTEGER = 27;
  int IDENT = 28;
  int STRING = 29;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"remove\"",
    "\"set\"",
    "\"add\"",
    "\"create\"",
    "\"replace\"",
    "\"getValue\"",
    "\"?INT\"",
    "\"?STR\"",
    "\"?BOOL\"",
    "\"void\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\";\"",
    "\":=\"",
    "\"+\"",
    "\"-\"",
    "\"+=\"",
    "\"-=\"",
    "\"\\n\"",
    "<DIGIT>",
    "<LETTER>",
    "<BOOLEAN>",
    "<INTEGER>",
    "<IDENT>",
    "<STRING>",
  };

}
