/* Generated By:JavaCC: Do not edit this line. IterationConstants.java */
package kmade.kmade.adaptatorFC.parserExpression;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface IterationConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WHILE = 4;
  /** RegularExpression Id. */
  int NOTWHILE = 5;
  /** RegularExpression Id. */
  int CROO = 6;
  /** RegularExpression Id. */
  int CROF = 7;
  /** RegularExpression Id. */
  int DIGIT = 8;
  /** RegularExpression Id. */
  int LETTER = 9;
  /** RegularExpression Id. */
  int NUMBER = 10;
  /** RegularExpression Id. */
  int STRING_LITERAL = 11;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"while\"",
    "\"notWhile\"",
    "\"[\"",
    "\"]\"",
    "<DIGIT>",
    "<LETTER>",
    "<NUMBER>",
    "<STRING_LITERAL>",
  };

}
