/* Generated By:JavaCC: Do not edit this line. IterationConstants.java */
package kmade.kmade.adaptatorFC.parserExpression;

public interface IterationConstants {

  int EOF = 0;
  int WHILE = 4;
  int NOTWHILE = 5;
  int CROO = 6;
  int CROF = 7;
  int DIGIT = 8;
  int LETTER = 9;
  int INTEGER = 10;
  int STRING_LITERAL = 11;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"while\"",
    "\"notWhile\"",
    "\"[\"",
    "\"]\"",
    "<DIGIT>",
    "<LETTER>",
    "<INTEGER>",
    "<STRING_LITERAL>",
  };

}
