/* Generated By:JavaCC: Do not edit this line. PreconditionConstants.java */
package kmade.kmade.adaptatorFC.parserExpression;

public interface PreconditionConstants {

  int EOF = 0;
  int EXIST = 4;
  int EXISTAT = 5;
  int EMPTY = 6;
  int NOMBRE = 7;
  int GETVALUE = 8;
  int UNKNOWN_INT = 9;
  int UNKNOWN_STRING = 10;
  int UNKNOWN_BOOLEAN = 11;
  int PARO = 12;
  int PARF = 13;
  int COMA = 14;
  int AND = 15;
  int OR = 16;
  int EQUAL = 17;
  int NOT_EQUAL = 18;
  int INF = 19;
  int SUP = 20;
  int INF_EQUAL = 21;
  int SUP_EQUAL = 22;
  int NOT = 23;
  int EOL = 24;
  int DIGIT = 25;
  int LETTER = 26;
  int BOOLEAN = 27;
  int INTEGER = 28;
  int IDENT = 29;
  int STRING = 30;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"isExist\"",
    "\"isExistAt\"",
    "\"isEmpty\"",
    "\"card\"",
    "\"getValue\"",
    "\"?INT\"",
    "\"?STR\"",
    "\"?BOOL\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"AND\"",
    "\"OR\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"not\"",
    "\"\\n\"",
    "<DIGIT>",
    "<LETTER>",
    "<BOOLEAN>",
    "<INTEGER>",
    "<IDENT>",
    "<STRING>",
  };

}
